CREATE TABLE IF NOT EXISTS dealers (id INT AUTO_INCREMENT PRIMARY KEY, login VARCHAR(100) UNIQUE, password VARCHAR(100), name VARCHAR(100), role ENUM('super','diller') DEFAULT 'diller', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO dealers (id,login,password,name,role) VALUES (1,'admin','$2b$10$Q/8b7VfwClHbFQyqZv/Bd.TDeTnAOkYm0Le/Kypyeoe3FgqfQndFC','BOSH ADMIN','super') ON DUPLICATE KEY UPDATE login='admin', password='$2b$10$Q/8b7VfwClHbFQyqZv/Bd.TDeTnAOkYm0Le/Kypyeoe3FgqfQndFC', name='BOSH ADMIN', role='super';
INSERT INTO settings (skey,svalue) VALUES ('pwd_migrated','1') ON DUPLICATE KEY UPDATE svalue='1';
-- Login: admin / Parol: admin123 (parol xavfsiz bcrypt formatida oldindan xeshlangan, avtomatik migratsiya o'chirib qo'yilgan shu qator uchun)
CREATE TABLE IF NOT EXISTS settings (skey VARCHAR(100) PRIMARY KEY, svalue TEXT);
INSERT IGNORE INTO settings (skey,svalue) VALUES ('channel','@paynet_xoliss'),('bot_token','8956274863:AAHhy99dkoeAK3RBzCQ4S78GtlWH3F8BLK8'),('template','1. Diller: {diller}
2. Ism: {ism}
3. Nomer: {nomer}
4. Operator: {operator}
5. Tarif: {tarif}');
CREATE TABLE IF NOT EXISTS paid_participants (id INT AUTO_INCREMENT PRIMARY KEY, phone VARCHAR(20) UNIQUE, pretty_phone VARCHAR(30), name VARCHAR(100) DEFAULT 'Nomalum', operator_name VARCHAR(50), tarif_name VARCHAR(100), is_paid TINYINT(1) DEFAULT 1, dealer_id INT DEFAULT 1, blacklisted TINYINT(1) DEFAULT 0, status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'approved', approved_by INT NULL, approved_at DATETIME NULL, reject_reason VARCHAR(255) NULL, is_blocked TINYINT(1) NOT NULL DEFAULT 0, block_reason VARCHAR(255) NULL, promo_count INT NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS duplicate_attempts (id INT AUTO_INCREMENT PRIMARY KEY, phone VARCHAR(20), pretty_phone VARCHAR(30), dealer_id INT, attempted_name VARCHAR(100), attempted_operator VARCHAR(50), attempted_tarif VARCHAR(100), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
-- Eslatma: agar bazangiz eskirgan bo'lsa (yuqoridagi yangi ustunlar/jadval yo'q bo'lsa), sayt birinchi ochilganda o'zi avtomatik qo'shib oladi (config.php ichidagi ensureSchema()). Qo'lda ishga tushirish shart emas.
-- Yangi funksiyalar: diller qo'shgan nomer avval status='pending' bo'lib "Kutilmoqda" sahifasida turadi, Bosh admin tasdiqlagach status='approved' bo'lib kanalga ketadi. Bosh admin o'zi qo'shsa to'g'ridan status='approved'.
-- Sozlamalar jadvalidagi qo'shimcha kalitlar: admin_chat_id (bosh adminga shaxsiy Telegram bildirishnoma), daily_limit_enabled va daily_limit_count (diller uchun kunlik qo'shish limiti).
CREATE TABLE IF NOT EXISTS operators (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50) UNIQUE);
CREATE TABLE IF NOT EXISTS tarifs (id INT AUTO_INCREMENT PRIMARY KEY, operator_name VARCHAR(50), name VARCHAR(100), price DECIMAL(12,2) NOT NULL DEFAULT 0, UNIQUE KEY uniq (operator_name,name));
CREATE TABLE IF NOT EXISTS winners (id INT AUTO_INCREMENT PRIMARY KEY, phone VARCHAR(20), name VARCHAR(100), dealer_id INT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT IGNORE INTO operators (name) VALUES ('Beeline');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Beeline','Hello 1');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Beeline','Hello 2');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Beeline','OPTIMAL');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Beeline','Oila Max');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Beeline','Oila Mega+');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Beeline','Standart+');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Beeline','Status Gold');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Beeline','Status Platinum');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Beeline','Status Silver');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Beeline','VIBE');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Beeline','Yorqin');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Beeline','Oila (A''zosi)');
INSERT IGNORE INTO operators (name) VALUES ('Ucell');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','Bor 90+90');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','Bor 70+70');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','Bor 110');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','Bor 160');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','TV Bor Ultra');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','TV Bor MAX');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','TV Bor');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','TV Bor Plus');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','Ovoz Plus');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','Foydali 45');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','Foydali 55');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','TV Doimiy 90');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','TV Doimiy 120');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','TV Doimiy 180');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','Ucell S FWA');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','Ucell M FWA');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','Ucell L FWA');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','Uydagi Cheksiz S');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','Uydagi Cheksiz M');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','Uydagi Cheksiz L');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','M2M Communal Pre');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','M2M Terminal Pre');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Ucell','M2M_Humo_Pre');
INSERT IGNORE INTO operators (name) VALUES ('Uztelecom');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Super Salom');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Bonus Super Salom');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Super Lux');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Bonus Super Lux');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Ideal Plus');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Bonus Ideal Plus');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Mobile Lux');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Mobile Elite');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Mobile Sport');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Mobile Mini M');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Optimal');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Balance');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Super Mini');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Ideal yil');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Data 300GB');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Data 600GB');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Data 1TB');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Uzmobile M2M yil');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','ONLINE Mobile');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Farzand');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Super Bonus');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Bayramona 35');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Uztelecom','Mini Voice');
INSERT IGNORE INTO operators (name) VALUES ('Humans');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Humans','15 000 UZS');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Humans','25 000 UZS');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Humans','30 000 UZS');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Humans','45 000 UZS');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Humans','50 000 UZS');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Humans','55 000 UZS');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Humans','65 000 UZS');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Humans','135 000 UZS');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Humans','5 000 000 UZS');
INSERT IGNORE INTO operators (name) VALUES ('Mobiuz');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Mobiuz','Orzu 90');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Mobiuz','Orzu 110');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Mobiuz','Orzu 150');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Mobiuz','Xotirjam 100');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Mobiuz','Xotirjam 80');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Mobiuz','Mazza 70');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Mobiuz','Terminal Yillik');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Mobiuz','L 55');
INSERT IGNORE INTO tarifs (operator_name,name) VALUES ('Mobiuz','M 45');
